### ISSUE TITLE
Profile Page Enhancements

### ISSUE THREAD

**Issue by myznikovgleb** [atomicai/patronusui#32]
### Description

Profile page contains only common user info. Let's enrich it with useful data and features

#### Search history
Search history contains
* Search queries
* Corresponding answers with the user rates

#### User settings
Empty for now

### Tasks
- [x] Save and display search history
- [ ] Allow to copy a search query in one click 
- [ ] Save rated answers to search history
